routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest'], function () {
    Route::get('/login',    'UserController@login')->       name('login');
    Route::post('/login',   'UserController@loginPost')->   name('login.post');
});

Route::group(['middleware' => 'isAdmin'], function () {
    Route::get('/logout',   'UserController@logout')->  name('logout');
    Route::get('/',         'HomeController@index')->   name('home');

    Route::group(['prefix' => 'category'], function () {
        Route::get ('',            'CategoryController@index')->   name('category.list');
        Route::get ('{id}',        'CategoryController@show')->    name('category.show')->     where('id', '[0-9]+');
        Route::post('',            'CategoryController@update')->  name('category.update');
        Route::get ('new',         'CategoryController@create')->  name('category.create');
        Route::post('new',         'CategoryController@store')->   name('category.store');
        Route::get ('delete/{id}', 'CategoryController@delete')->  name('category.delete')->   where('id', '[0-9]+');
    });

    Route::group(['prefix' => 'product'], function () {
        Route::get('',            'ProductController@index')->   name('product.list');
        Route::get('{id}',        'ProductController@show')->    name('product.show')->     where('id', '[0-9]+');
        Route::post('',           'ProductController@update')->  name('product.update');
        Route::get('new',         'ProductController@create')->  name('product.create');
        Route::post('new',        'ProductController@store')->   name('product.store');
        Route::get('delete/{id}', 'ProductController@delete')->  name('product.delete')->   where('id', '[0-9]+');
    });

    Route::group(['prefix' => 'user'], function () {
        Route::get ('',       'UserController@index')->   name('user.list');
        Route::get ('{user}', 'UserController@show')->    name('user.show')->   where('user', '[0-9]+');
        Route::post('',       'UserController@update')->  name('user.update');
    });

    Route::group(['prefix' => 'delivery'], function () {
        Route::get ('',                  'DeliveryController@index')->  name('delivery.list');
        Route::get ('{delivery}',        'DeliveryController@show')->   name('delivery.show')->     where('delivery', '[0-9]+');
        Route::post('{delivery}',        'DeliveryController@update')-> name('delivery.update')->   where('delivery', '[0-9]+');
        Route::get ('new',               'DeliveryController@create')-> name('delivery.create');
        Route::post('new',               'DeliveryController@store')->  name('delivery.store');
        Route::get ('delete/{delivery}', 'DeliveryController@delete')-> name('delivery.delete')->   where('delivery', '[0-9]+');
    });

    Route::group(['prefix' => 'order'], function () {
        Route::get('', 'OrderController@index')         ->name('order.list');
        Route::get('{order}', 'OrderController@show')   ->name('order.show')->where('order', '[0-9]+');
    });

    Route::get('/ajax/image/delete/{id}', "ImageController@ajaxDelete");
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', "MainController@index")->name('home');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', 'AuthController@register')->name('register');
    Route::post('/register', 'AuthController@registerPost')->name('registerPost');

    Route::get('/login', 'AuthController@login')->name('login');
    Route::post('/login', 'AuthController@loginPost')->name('Post');
});

Route::get('/logout', 'AuthController@logout')->name('logout');

Route::get('/shop/category/{slug}', 'ShopController@category')->name('category');
Route::get('/shop/category/{slug}/{subslug}', 'ShopController@category')->name('subcategory');
Route::get('/shop/product/{category}/{slug}', 'ShopController@product')->name('product');

Route::group(['prefix' => 'cart'], function () {
    Route::post('/add', 'ShopController@addToCart')->name('addToCart');
    Route::get('/remove/{id}', 'ShopController@removeProduct');
    Route::post('/change', 'ShopController@changeQuantity');
    Route::get('/', 'ShopController@showCart')->name('cart.show');
    Route::post('/', 'ShopController@submitOrder')->name('cart.submit');
});

app/Models/Order.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use SoftDeletes;


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function delivery()
    {
        return $this->hasOne(OrderDelivery::class);
    }

    public function status()
    {
        return $this->belongsTo(OrderStatus::class, 'status_id', 'id');
    }

    public function getNumberAttribute()
    {
        return "№" . $this->attributes['id'] . ' от ' . Carbon::parse($this->attributes['created_at'])->format('d.m.Y');
    }

    public function getDataAttribute()
    {
        return json_decode($this->attributes['data']);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::orderBy('created_at', 'DESC')->paginate(50);

        return view('admin.order.list', compact('orders'));
    }

    public function show(Order $order)
    {
        return view('admin.order.show', compact('order'));
    }
}

resources/views/admin/order/list.blade.php
@extends('admin.layout')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header bg-gradient-primary">
                        <h3 class="card-title mt-2">Заказы</h3>
                        <div class="card-tools">
                            {{--<a href="{{ route('admin.product.create') }}" class="btn btn-default">Новый товар</a>--}}
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <th>Номер</th>
                            <th>Статус</th>
                            <th>Заказчик</th>
                            <th>Себестоимость</th>
                            <th>Сумма</th>
                            <th></th>
                            </thead>
                            <tbody>
                            @foreach($orders as $order)
                                <tr>
                                    <td>{{ $order->number }}</td>
                                    <td>{{ $order->status->name_ru }}</td>
                                    <td>{{ $order->data->name }}</td>
                                    <td>{{ $order->income_total }}</td>
                                    <td>{{ $order->total }}</td>
                                    <td>
                                        <a href="{{ route('admin.order.show', $order->id) }}"><i class="fas fa-edit"></i></a>
                                        <a href="{{ route('admin.product.delete', $order->id) }}"><i class="fas fa-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <ul class="pagination pagination-sm m-0 float-right">
                            {{ $orders->links() }}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/order/show.blade.php
@extends('admin.layout')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header bg-gradient-primary">
                    <h3 class="card-title mt-2">Заказ {{ $order->number }}</h3>
                    <div class="card-tools">
                        {{--<a href="{{ route('admin.product.create') }}" class="btn btn-default">Новый товар</a>--}}
                    </div>
                </div>
                <div class="card-body">
                    <h3>Состав заказа</h3>
                    <table class="table">
                        <thead>
                        <th>#</th>
                        <th>Наименование</th>
                        <th>количество</th>
                        <th>Цена</th>
                        <th>Сумма</th>
                        </thead>
                        <tbody>
                        @php $i = 1 @endphp
                        @foreach($order->items as $item)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $item->product->name }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td title="Входная цена: {{ $item->income_price }}">{{ $item->price }}</td>
                            <td title="Входная сумма: {{ $item->income_price * $item->quantity }}. Доход: {{ $item->price * $item->quantity - $item->income_price * $item->quantity }}">{{ $item->price * $item->quantity }}</td>
                        </tr>
                        @endforeach
                        <tr>
                            <td>{{ $order->delivery->name }}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>{{ $order->delivery->price }}</td>
                        </tr>
                        <tr>
                            <td>Итого:</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td title="Себестоимость: {{ $order->income_total }}. Доход: {{ $order->total - $order->delivery->price - $order->income_total }}">{{ $order->total }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <h3>Данные покупателя</h3>
                    <table class="table">
                        <tbody>
                        <tr>
                            <td>Имя:</td>
                            <td>{{ $order->data->name }}</td>
                        </tr>
                        <tr>
                            <td>Email:</td>
                            <td>{{ $order->data->email }}</td>
                        </tr>
                        <tr>
                            <td>Телефон:</td>
                            <td>{{ $order->data->phone }}</td>
                        </tr>
                        <tr>
                            <td>Адрес:</td>
                            <td>{{ $order->data->address }}</td>
                        </tr>
                        <tr>
                            <td>Комментарий:</td>
                            <td>{{ $order->data->comment }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <ul class="pagination pagination-sm m-0 float-right">

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection